#!/usr/bin/env python
import sys
import os
import subprocess
import shutil
from django.core import management
#from project import settings


def buildproject(argv=[]):
    if len(argv) < 2:
        proj_dir = os.path.abspath(os.getcwd())
        in_proj_dir = True
    else:
        proj_dir = os.path.abspath(os.path.join(os.getcwd(), argv[1]))
        in_proj_dir = False
    if not os.path.isfile(os.path.join(proj_dir, 'manage.py')):
        print "Not a valid Django project"
        return
    boilerplate_dir = os.path.join(proj_dir, '..', 'html5boilerplate')

    print 'Removing old \'publish\' directories...'
    if os.path.exists(os.path.join(proj_dir, 'templates_publish')):
        shutil.rmtree(os.path.join(proj_dir, 'templates_publish'))
        os.mkdir(os.path.join(proj_dir, 'templates_publish'))
    if os.path.exists(os.path.join(proj_dir, 'static_publish')):
        shutil.rmtree(os.path.join(proj_dir, 'static_publish'))
        os.mkdir(os.path.join(proj_dir, 'static_publish'))
    if os.path.exists(os.path.join(proj_dir, 'static_tmp')):
        shutil.rmtree(os.path.join(proj_dir, 'static_tmp'))
        
    print 'Running collectstatic...'
    #management.setup_environ(settings)
    #management.execute_from_command_line(['collectstatic', '--noinput',])
    
    #from django.contrib.staticfiles.management.commands.collectstatic import Command
    #collectstatic_command = Command()
    #collectstatic_command.handle_noargs(interactive=False)
    
    if in_proj_dir:
        subprocess.call(['python', 'manage.py', 'collectstatic', '--noinput'])
    else:
        subprocess.call(['python', '%s/manage.py'%argv[1], 'collectstatic', '--noinput'])
    
    os.rename(os.path.join(proj_dir, 'static_publish'), os.path.join(proj_dir, 'static_tmp'))
        
    cwd = os.getcwd()
    os.chdir(os.path.join(boilerplate_dir, 'build'))
    print 'Starting Ant build...'
    try:
        subprocess.call(['ant', '-version'])
    except OSError:
        print 'You do not appear to have \'ant\' installed'
        return
    #retcode = subprocess.call(['ant', 'minify'])
    retcode = subprocess.call(['ant', 'build'])
    if retcode > 0:
        print 'Ant build failed'
        return
    os.chdir(cwd)
    
    print 'Moving minified templates to Django project (templates_publish)...'
    os.rename(os.path.join(boilerplate_dir, 'publish', argv[1], 'templates'), os.path.join(proj_dir, 'templates_publish'))
    
    print 'Moving CSS, JS and images into Django project...'
    os.rename(os.path.join(boilerplate_dir, 'publish', argv[1], 'static_tmp'), os.path.join(proj_dir, 'static_publish'))
    
    shutil.rmtree(os.path.join(boilerplate_dir, 'publish'))
    shutil.rmtree(os.path.join(proj_dir, 'static_tmp'))
    
    
if __name__ == "__main__":
    buildproject(sys.argv)

